name: Build and Deploy

on:
  push:
    branches:
      - 'stage-worknest'  # Trigger on push to the 'stage-compass' branch
      - 'publish'        # Trigger on push to the 'publish' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use the PAT for repository checkout

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Adjust to your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Commit and Push Changes
        if: github.actor != 'github-actions[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist -f
          git commit -m "Deploy build [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.ref_name }}

